<a href="https://colab.research.google.com/github/raifernandesz/Repositorio_Base_RaianeFernandes/blob/main/exercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

funcionarios = {
    "nome": [
        "Ana Souza", "Bruno Lima", "Carla Ferreira", "Diego Santos", "Eduarda Nascimento",
        "Felipe Almeida", "Giovana Ramos", "Henrique Costa", "Isabela Araujo", "João Pereira",
        "Karina Oliveira", "Lucas Rodrigues", "Mariana Machado", "Nathan Silva", "Olívia Barbosa"
    ],
    "unidade": [
        2, 1, 3, 2, 1,
        3, 1, 2, 3, 1,
        2, 3, 1, 3, 2
    ],
    "escala_noturna": [
        False, True, False, True, False,
        True, False, True, False, True,
        False, True, False, True, False
    ],
    "vendas": [
        18754.32, 24321.89, 19876.45, 27543.22, 15789.66,
        29123.10, 22345.99, 26789.40, 19456.78, 28345.55,
        17654.12, 23876.99, 20543.70, 29654.88, 18321.44
    ]
}



df = pd.DataFrame(funcionarios)
df
# df['unidade'].value_counts
#df['escala_noturna'].value_counts()
# resultado = df[df['nome'] == 'Henrique Costa']
# print(resultado)
# separar a diurna em uma variavel
# separar a noturna em uma variavel
# escala_noturna = sum(df['escala_noturna' == 'true'])


# df[df['vendas'] < 20000]





#df['nome']
#df['unidade']
#df['escala_noturna']
#df['vendas']


#df.info()

                  nome  unidade  escala_noturna    vendas
0            Ana Souza        2           False  18754.32
1           Bruno Lima        1            True  24321.89
2       Carla Ferreira        3           False  19876.45
3         Diego Santos        2            True  27543.22
4   Eduarda Nascimento        1           False  15789.66
5       Felipe Almeida        3            True  29123.10
6        Giovana Ramos        1           False  22345.99
7       Henrique Costa        2            True  26789.40
8       Isabela Araujo        3           False  19456.78
9         João Pereira        1            True  28345.55
10     Karina Oliveira        2           False  17654.12
11     Lucas Rodrigues        3            True  23876.99
12     Mariana Machado        1           False  20543.70
13        Nathan Silva        3            True  29654.88
14      Olívia Barbosa        2           False  18321.44

# Nova seção